name: Fault check PIN Comparison

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs: 
      name: 
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  fault_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install thumbv6 target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: thumbv6m-none-eabi 
      - name: Install Rainbow
        run: python3 -m pip install git+https://github.com/Ledger-Donjon/rainbow@fix_function_discovery
      - name: Run Fault check
        run: python3 fi_check.py test_fi_hard test_fi_hard2 --cli
